
openapi: 3.0.0
info:
  title: Blocks Management Service
  version: 1.0.0
paths:
  /blocks:
    get:
      summary: List all blocks
      responses:
        '200':
          description: A list of blocks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Block'
    post:
      summary: Create a new block
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Block'
      responses:
        '201':
          description: Block created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Block'
  /blocks/{blockId}:
    get:
      summary: Get a block by ID
      parameters:
        - name: blockId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A block object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Block'
components:
  schemas:
    Block:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        type:
          type: string
        code:
          type: string
